baseURL = "https://lonelyhackers.club"
languageCode = "en-us"
title = "Lonely Hackers Club"
theme = "retrofulhugo-lhc"

[Params]
  logo = "lhc_logo_dc31.png"
  commit = false
  favicon = "favicon.ico"

[Author]
  handle = "LHC"
  github = "largehadroncollider/lhcSiteSource"
  twitter = "L0nelyH4ckers"